services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - chronoflownetwork

  database:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - chronosflow_db_data:/var/lib/postgresql/data
    networks:
      - chronoflownetwork

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - chronoflownetwork

volumes:
  chronosflow_db_data:

networks:
  chronoflownetwork:
    driver: bridge