-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

ALTER TABLE IF EXISTS public.projects DROP CONSTRAINT IF EXISTS creator_id_fk;

ALTER TABLE IF EXISTS public.tasks DROP CONSTRAINT IF EXISTS project_id_fk;

ALTER TABLE IF EXISTS public.tasks DROP CONSTRAINT IF EXISTS assigned_user_id_fk;



DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    name character varying(255) NOT NULL,
    username character varying NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    created_at date NOT NULL,
    last_login date NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT users_unique_username UNIQUE (username),
    CONSTRAINT users_unique_email UNIQUE (email)
);

DROP TABLE IF EXISTS public.projects;

CREATE TABLE IF NOT EXISTS public.projects
(
    id serial,
    title character varying(255) NOT NULL,
    description character varying(255),
    creator_id integer NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.tasks;

CREATE TABLE IF NOT EXISTS public.tasks
(
    id serial,
    title character varying(255) NOT NULL,
    description character varying(255),
    start_date date NOT NULL,
    end_date date NOT NULL,
    status "STATUS" NOT NULL,
    priority "PRIORITY" NOT NULL,
    project_id integer NOT NULL,
    assigned_user_id integer,
    parent_task_id integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.projects
    ADD CONSTRAINT creator_id_fk FOREIGN KEY (creator_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.tasks
    ADD CONSTRAINT project_id_fk FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.tasks
    ADD CONSTRAINT assigned_user_id_fk FOREIGN KEY (assigned_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;

END;