name: Docker Compose E2E Tests

on:
  pull_request:
    branches:
      - main

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          services: |
            database
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_database
      
      - name: Test e2e on backend
        run: |
          cd backend
          npm install
          npx prisma generate && npx prisma db push
          npx jest test/app.e2e-spec.ts
        env:
          DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_database
