name: Docker Compose E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    services:
      # Define a service for the Docker container
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2
        with:
          version: 'latest'

      - name: Start Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build

      - name: Wait for services to be ready
        run: |
          sleep 10

      - name: Run E2E tests
        run: |
          # Execute os testes E2E contra o seu servidor ou frontend
          cd backend
          npm run test:e2e

      - name: Shut down Docker Compose
        run: |
          docker-compose down
